from datetime import datetime
import csv
import math


class Song:
    def __init__(self, songid, songtype, title, series, beginner, expert, ultimate, supreme):
        self.songid = songid
        self.songtype = songtype
        self.title = title
        self.series = series
        self.beginner = beginner
        self.expert = expert
        self.ultimate = ultimate
        self.supreme = supreme
        self.unquotedtitle = title.replace("\"", "")

def get_series_nav_html():
    content = ""
    lastseries = ""
    i = 0
    for song in song_list:
        if not song.series == lastseries:
            lastseries = song.series
            content += "<a href=\"#qn-s" + str(i) + "\">" + song.series.replace("Bra?", "Bra&#9733;") + "</a><br>\n"
            i += 1
    return content

last_series = ""
series_index = 0
song_list = []
datestring = datetime.today().strftime("%B %e, %Y at %I:%M %p")
if "at 0" in datestring:
    datestring = datestring.replace("at 0", "at ")
pageheader = "---\npermalink: /records/tfbl-scores/\nlayout: wnesenior\ntitle: Theatrhythm Final Bar Line Scores\nbase_url: /records/\nlast_updated: "
pageheader += datestring + "\n---\n\n"
signaturehtml = "<!-- Generated by https://github.com/egartley/records !-->\n"
signaturehtml += "<link href=\"/resources/css/tfbl-scores-style.css\" rel=\"stylesheet\" type=\"text/css\">\n"
signaturehtml += "<p>These are my current scores in the game <i>Theatrhythm Final Bar Line</i> for PlayStation. Each song "
signaturehtml += "has the score listed for the three difficulties along with the stage type next to the title. For the most part, the "
signaturehtml += "awkward capitialization and formatting of the titles has been perserved from the game, except for "
signaturehtml += "titles that have the series name prepended to them (mainly the FFVII Remake songs). None of the DLC songs are included.</p>\n"
listinghtml = "<div class=\"songcard-container flex col\">\n"

# build list from csv
with open("tfbl-scores.csv", mode="r") as tfblcsv:   
  file = csv.reader(tfblcsv)
  firstline = True
  for gl in file:
      if firstline:
          firstline = False
          continue
      song = Song(int(gl[0]), str(gl[3]), str(gl[2]), str(gl[1]), int(gl[4]), int(gl[5]), int(gl[6]), int(gl[7]) if not str(gl[7]) == "-" else -1)
      song_list.append(song)

# build navigate by series html
oldlh = listinghtml
prepend = "<span><h2 style=\"display:inline\">Navigate by Series</h2><span class=\"showhide\" "
prepend += "onclick=\"p=$('p#navseries');t=$(this);if(p.is(':visible')){p.slideUp();t.html('Show')}else{p.slide"
prepend += "Down();t.html('Hide')}\">Hide</span></span>\n<p id=\"navseries\">" + get_series_nav_html() + "\n"
listinghtml = prepend + oldlh

# build listing html
for song in song_list:
    start = "<div class=\"songcard flex col\">"
    if not last_series == song.series:
        last_series = song.series
        start += "<span class=\"qn-link\" id=\"qn-s" + str(series_index) + "\"></span>"
        series_index += 1
    content = "<span class=\"songcard-title flex\">" + song.title.replace("Bra?", "Bra&#9733;")
    content += "<span class=\"songcard-" + song.songtype.lower() + "\">" + song.songtype + "</span>"
    content += "</span><span class=\"songcard-series\">" + song.series.replace("Bra?", "Bra&#9733;") + "</span><div class=\"songcard-scores flex\">"
    content += "<span class=\"songcard-beginner\">" + str(song.beginner) + "</span><span class=\"songcard-expert\">" + str(song.expert) + "</span>"
    content += "<span class=\"songcard-ultimate\">" + str(song.ultimate) + "</span>"
    if not song.supreme == -1:
        content += "<span class=\"songcard-supreme\">" + str(song.supreme) + "</span>"
    content += "</div>"
    end = "</div>\n"
    listinghtml += start + content + end
listinghtml += "</div>\n"

# output file
with open("tfbl-scores.html", mode="w") as outfile:
    outfile.write(pageheader + signaturehtml + listinghtml)

print("Done!")
